# Generated by Django 4.2.5 on 2023-11-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EatTrack',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eat_track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipmentneeded',
            fields=[
                ('equipmentneededid', models.AutoField(db_column='EquipmentNeededID', primary_key=True, serialize=False)),
                ('equipmentneededname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EquipmentNeededName', max_length=255)),
            ],
            options={
                'db_table': 'EquipmentNeeded',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exerciseid', models.AutoField(db_column='ExerciseID', primary_key=True, serialize=False)),
                ('exercisename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ExerciseName', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', null=True)),
                ('difficultylevel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DifficultyLevel', max_length=20, null=True)),
                ('repetitions', models.IntegerField(blank=True, db_column='Repetitions', null=True)),
                ('sets', models.IntegerField(blank=True, db_column='Sets', null=True)),
                ('durationinseconds', models.IntegerField(blank=True, db_column='DurationInSeconds', null=True)),
                ('caloriesburnedperminute', models.DecimalField(blank=True, db_column='CaloriesBurnedPerMinute', decimal_places=2, max_digits=5, null=True)),
                ('targetedmuscles', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TargetedMuscles', max_length=255, null=True)),
                ('imageurl', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ImageURL', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Exercises',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseSuggestions',
            fields=[
                ('user_pred', models.OneToOneField(db_column='user_pred', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='body.userpred')),
                ('reps', models.IntegerField(blank=True, db_column='Reps', null=True)),
                ('sets', models.IntegerField(blank=True, db_column='Sets', null=True)),
            ],
            options={
                'db_table': 'Exercise_suggestions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercisetype',
            fields=[
                ('exercisetypeid', models.AutoField(db_column='ExerciseTypeID', primary_key=True, serialize=False)),
                ('exercisetypename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ExerciseTypeName', max_length=255)),
            ],
            options={
                'db_table': 'ExerciseType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musclegroup',
            fields=[
                ('musclegroupid', models.AutoField(db_column='MuscleGroupID', primary_key=True, serialize=False)),
                ('musclegroupname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MuscleGroupName', max_length=255)),
            ],
            options={
                'db_table': 'MuscleGroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutritions',
            fields=[
                ('nutrition_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, primary_key=True, serialize=False)),
                ('carbohydrates_100g', models.FloatField(blank=True, null=True)),
                ('energy_kcal_100g', models.FloatField(blank=True, db_column='energy-kcal_100g', null=True)),
                ('fat_100g', models.FloatField(blank=True, null=True)),
                ('proteins_100g', models.FloatField(blank=True, null=True)),
                ('sugars_100g', models.FloatField(blank=True, null=True)),
                ('sodium_100g', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutritions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetailEatTrack',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='body.eattrack')),
                ('serving_size', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail_eat_track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('barcode', models.OneToOneField(db_column='barcode', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='body.nutritions')),
                ('brand', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
