# Generated by Django 4.2.5 on 2023-10-17 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_countrycode_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryCode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
